version: "3.7"
services:
  app:
    build:
      args:
        user: imtiaj
        uid: 9980
      context: ./
      dockerfile: Dockerfile
    image: edenschool
    container_name: edenschool-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - edenschool
      - net

  db:
    image: mysql:8.0
    container_name: edenschool-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - edenschool

  nginx:
    image: nginx:alpine
    container_name: edenschool-nginx
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: api.edenresidentialschool.edu.bd
      LETSENCRYPT_HOST: api.edenresidentialschool.edu.bd
      VIRTUAL_PORT: 80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - edenschool
      - net

networks:
  edenschool:
    driver: bridge
  net:
    external: true
